cyan/new:
  active: true
  history:
    - version: 12
      time: 2025-09-20T04:16:50.929573Z
      answers:
        cyan/new/processor/0:
          type: String
          value: cyan/default
        cyan/new/username:
          type: String
          value: atomi
        cyan/new/email:
          type: String
          value: admin@atomi.cloud
        cyan/new/more-processors/1:
          type: String
          value: no
        cyan/new/project:
          type: String
          value: https://github.com/AtomiCloud/ketone.helm
        cyan/new/create:
          type: String
          value: Template
        cyan/new/more-tags/0:
          type: String
          value: yes
        cyan/new/description:
          type: String
          value: AtomiCloud's helm template
        cyan/new/more-processors/0:
          type: String
          value: yes
        cyan/new/more-tags/1:
          type: String
          value: no
        cyan/new/language:
          type: String
          value: Typescript
        cyan/new/source:
          type: String
          value: https://github.com/AtomiCloud/ketone.helm.git
        cyan/new/more-plugins/0:
          type: String
          value: no
        cyan/new/name:
          type: String
          value: Helm
        cyan/new/tag/0:
          type: String
          value: atomi
      deterministic_states: {}
atomi/workspace:
  active: true
  history:
    - version: 20
      time: 2025-09-20T04:18:17.086559Z
      answers:
        atomi/workspace/enable-docker:
          type: Bool
          value: true
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/platform:
          type: String
          value: ketone
        atomi/workspace/service:
          type: String
          value: helm
      deterministic_states: {}
    - version: 21
      time: 2025-09-20T08:02:47.069358Z
      answers:
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/enable-docker:
          type: Bool
          value: true
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/service:
          type: String
          value: helm
        atomi/workspace/platform:
          type: String
          value: ketone
        atomi/workspace/enable-helm:
          type: Bool
          value: false
      deterministic_states: {}
atomi/nix-init:
  active: true
  history:
    - version: 13
      time: 2025-09-20T04:17:58.544143Z
      answers:
        init-type:
          type: String
          value: CyanPrint Bun
      deterministic_states: {}
    - version: 14
      time: 2025-09-20T08:02:51.664181Z
      answers:
        init-type:
          type: String
          value: CyanPrint Bun
      deterministic_states: {}
atomi/cyan:
  active: true
  history:
    - version: 12
      time: 2025-09-20T09:15:38.576652Z
      answers:
        atomi-cyan/service:
          type: String
          value: helm
        atomi-cyan/platform:
          type: String
          value: ketone
        atomi-cyan/template-description:
          type: String
          value: AtomiCloud's helm template
        atomi-cyan/template-name:
          type: String
          value: Helm
      deterministic_states: {}
