version: '3'

env:
  SOS_PROJECT_ID: '1cffa31e-7653-4c0d-9a18-9914a2dbc30b'
  RELEASE_NAME: sulfoxide-gold

includes:
  util: tasks/Taskfile.util.yaml
  base: tasks/Taskfile.cluster.yaml
  # lapras:
  #   taskfile: tasks/Taskfile.cluster.yaml
  #   vars:
  #     LANDSCAPE: lapras
  # entei:opal:
  #   taskfile: tasks/Taskfile.cluster.yaml
  #   vars:
  #     LANDSCAPE: entei
  #     CLUSTER: opal

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update
