apiVersion: v1
kind: Service
metadata:
  name: {{ include "let___platform___-let___service___.fullname" . }}
  labels: {{- include "let___platform___-let___service___.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "let___platform___-let___service___.selectorLabels" . | nindent 4 }}
